# Create PVC for game state data.
# Assuming dynamic PV creation on local storage with Rancher
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-pv-claim
  namespace: valheim
  labels:
    app: valheim-server
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
# Create Deployment for pod.
# First try with hostport.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valheim-server
  namespace: valheim
  labels:
    app: valheim-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valheim-server
  template:
    metadata:
      labels:
        app: valheim-server
    spec:
      containers:
      - name: valheim-server
        image: quay.io/pstrick/TBD:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 2456
            protocol: UDP
            hostPort: 2456
          - containerPort: 2457
            protocol: UDP
            hostPort: 2457
          - containerPort: 2458
            protocol: UDP
            hostPort: 2458
        env:
          - name: SERVER_NAME
            value: "ValheimServer"
          - name: SERVER_WORLD
            value: "Valhalla"
          - name: SERVER_PASSWORD
            value: "secret"
          - name: SERVER_PORT
            value: "2456"
          - name: UPDATE_ON_RESTART
            value: "1"
        volumeMounts:
          - mountPath: /data
            name: valheim-data
      volumes:
        - name: valheim-data
          persistentVolumeClaim:
            claimName: valheim-pv-claim