apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valheim
  namespace: valheim
spec:
  serviceName: valheim
  replicas: 1
  selector:
    matchLabels:
      app: valheim
  template:
    metadata:
      labels:
        app: valheim
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: valheim-server
        image: quay.io/pstrick/valheim:latest 
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 2456
            protocol: UDP
          - containerPort: 2457
            protocol: UDP
          - containerPort: 2458
            protocol: UDP
        env:
          - name: SERVER_NAME
            value: "ValheimServer"
          - name: SERVER_WORLD
            value: "Valhalla"
          - name: SERVER_PASSWORD
            value: "secret"
          - name: SERVER_PORT
            value: "2456"
          - name: UPDATE_ON_RESTART
            value: "1"
        volumeMounts:
          - mountPath: /data
            name: valheim-data
  volumeClaimTemplates:
    - metadata:
        name: valheim-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
